import { PolicyChatProvider } from "@/adapters/mock/MockChatProvider";
import { MockCompanyRepository } from "@/adapters/mock/MockCompanyRepository";
import { MockContractReviewProvider } from "@/adapters/mock/MockContractReviewProvider";
import { MockRiskProvider } from "@/adapters/mock/MockRiskProvider";
import { RealCompanyRepository } from "@/adapters/real/RealCompanyRepository";
import { RealContractReviewProvider } from "@/adapters/real/RealContractReviewProvider";
import { MlRiskProvider } from "@/adapters/real/MlRiskProvider";
import { getCompanyDataMode, getContractDataMode } from "@/config/dataMode";
import type { CompanyRepository } from "@/domain/company";
import type { ChatProvider } from "@/domain/chat";
import type { ContractReviewProvider } from "@/domain/contract";
import type { RiskProvider } from "@/domain/risk";

const mockCompanyRepository = new MockCompanyRepository();
const mockRiskProvider = new MockRiskProvider();
const realCompanyRepository = new RealCompanyRepository();
const realRiskProvider = new MlRiskProvider();

export function getCompanyRepository(): CompanyRepository {
  return getCompanyDataMode() === "real" ? realCompanyRepository : mockCompanyRepository;
}

export function getRiskProvider(): RiskProvider {
  return getCompanyDataMode() === "real" ? realRiskProvider : mockRiskProvider;
}

export function getChatProvider(): ChatProvider {
  // This provider supplies deterministic policy metadata and fallback copy.
  // Final user-facing chat text is generated by DualLlmChatProvider.
  return new PolicyChatProvider(getCompanyRepository(), getRiskProvider());
}

export function getContractReviewProvider(): ContractReviewProvider {
  return getContractDataMode() === "real" ? new RealContractReviewProvider() : new MockContractReviewProvider();
}
